***Civ 2000 Improvements Text File - Copyright (c) 1995 MicroProse Software, Inc. ***
***Alteration of this file may cause the Civilopedia to malfunction...***
Aqueduct
A major obstacle to population growth and expansion in early cities was the scarcity of water. In many cases, the solution to this problem was an aqueduct. Aqueducts were large, elevated stone "canals" through which water from nearby hills and mountains was channeled into the city. Aqueducts allowed cities to grow much larger by significantly increasing the amount of available water. At the same time aqueducts reduced the chance of contracting water-borne diseases, by reducing the dependence on stagnant ponds and wells as water sources. Aqueducts also allowed cities to be built in normally inhospitable environments, such as deserts, by providing an outside water source. Modern day Los Angles, for example, obtains its water supply from the Colorado River, through a system of aqueducts over 200 miles long.

Bank
A highly developed banking system is one of the cornerstones of an advanced civilization. Banks lend money to individuals or groups, providing capital for industrial and real estate development. Banks also contribute to the economic growth of a city or region by stimulating the development of production facilities. Individual citizens can also benefit by investing their own surplus money in the bank and  earning interest on it.

Barracks
Warfare has been a recurring phenomenon throughout the history of mankind, and it continues to plague the world today. Although war is not a desirable situation, it is important that even the most peaceful of societies be prepared for the possibility of war. When warring nations are closely matched in technology and manpower, battles are usually won by the army with the best training. Military schools and academies exist all over the world, established for the purpose of training military personnel in the latest methods, tactics, and technology. Men and women who graduate from such facilities possess higher than average command and military and technological skills, making them more effective in combat situations.

Cathedral
Throughout the Dark Ages that followed the fall of the Roman Empire, the Christian Church was a major influence in the revival of European civilization. In recognition of the expanding influence of the church, great cathedrals were built in the largest towns and cities, to act as centers of religious study and worship. In addition to their religious significance, cathedrals acted as the center of social and cultural activity in the town. They brought great pride, stability, and tradition to the citizens of the community.

City Walls
Before the establishment of centralized governments capable of supporting strong, national armies, individual cities were left to fend for themselves when it came to defense. As a result, many cities constructed city walls to protect against raiders and bandits. City walls represented a major investment in both time and materials, requiring years to complete and constant repairs to maintain their strength and integrity. However, these walls turned the city into a fortress capable of withstanding all but the most determined attack.

Colosseum
The original colosseum provided entertainment for the common people of Roman society by presenting them with spectacles and events as a temporary escape from day-to-day life. This concept has been revived in the 20th Century. Modern-day stadiums and civic centers provide an arena for entertainment ranging from concerts to professional sporting events. Although the violent spectacle of gladiatorial combat is a thing of the past, today's colosseums still provide entertainment and diversion for the masses.

Courthouse
As kingdoms and empires expanded, it became increasingly difficult for the rulers to maintain control over the more distant regions of their realm. To ensure that the far-flung cities of the empire contributed their expected share of duties and taxes to the government, local magistrates and courts were established. In the courthouse, the ruler's representatives listened to the grievances of the people and defined and enforced the laws that governed social interaction. This reduced crime, and thereby kept the local population productive.

Factory
Early examples of factory-like production, where a number of individuals work cooperatively to produce goods for sale or trade, can be found as far back as ancient Greece and Rome. Modern factories, however, evolved from the concept of specialized labor, where each worker performed a single step in the overall production of an item. This specialization allows factories to increase the speed and efficiency of the manufacturing process, far surpassing earlier means of production. The development of the factory system as a means of production played a key role in the Industrial Revolution.

Granary
Early humans were nomadic, settling in specific regions only for brief periods of time. When the food supply was exhausted in one area, the nomads would move on to search for more. Cities became possible only when the development of agriculture made the supply of food more abundant and dependable. However, cities still needed a way to keep the food supply stable throughout all four seasons. To do so, the citizens had to come up with a way to store seasonal crops for later use. The Granary was designed for the storage and protection of surplus food. Food storage technology meant that a smaller percentage of the population could produce and store enough food for everyone, allowing the remainder to pursue other jobs and activities.

Hydro Plant
One alternative to power generation utilizing coal or petroleum fuels is the hydroelectric power plant. This facility utilizes the energy of rapidly moving water to turn the turbines of its generators and produce electricity. In locations where a source of moving water is available, hydro plants offer a clean, safe alternative to coal, petroleum, and nuclear power generation. Hydro plants have their own set of  environmental dangers, however. The disruption of a river's normal flow and the massive flooding of the land behind the facility's dam can destroy the habitat of the wildlife inhabiting the river basin.

Library
The development of writing meant that the accumulated knowledge of a society could be written down and stored rather than memorized and passed along by word of mouth. The accumulated written material was stored in a library. The libraries of the ancient world, especially those at Alexandria and Pergamum, became leading centers of science and scholarship. The librarians actively collected the books of the world, accelerating the spread of knowledge.

Manufacturing Plant
Manufacturing plants are large industrial complexes that produce goods of all types, although they are generally used to produce durable consumer goods such as automobiles. Essentially, a manufacturing plant is a large, sophisticated factory that employs specialization of labor, complex machinery, and assembly lines to gain efficiency and economies of scale. This combination of manpower and automation increases productivity and reduces production costs.

Marketplace
As cities grew and prospered, trade between the farmers, artisans, and craftsmen who lived in the vicinity contributed to the economic health of the city. It soon became apparent that the best way for conducting trade within the city was to have a central location, or marketplace, where the people offering goods and services, or seeking them, could meet and conduct business. As a city's marketplace grew larger and more active, the economic vitality of the city grew as well.

Mass Transit
Within a few decades of the invention of the automobile, the horse-drawn carriage disappeared from city streets. Along with all the advantages offered by the automobile, this new means of transportation quickly became a significant source of air pollution. As larger cities became more crowded, the number of cars increased, making travel difficult and adding to the pollution problem as automobile traffic clogged the streets. The development of mass transit systems, including busses, trolleys, subways, and light rail, led to a reduction in traffic and, as a result, a reduction in air pollution.

Nuclear Power Plant
Nuclear power plants utilize radioactive materials and the process of nuclear fission to generate the heat and steam needed to run electrical generators and produce electricity. Because nuclear power doesn't cause the air pollution associated with the burning of coal or petroleum products, this means of generating power is considered a viable alternative energy source. However, the toxic nature of the byproducts produced by the fission process creates serious problems of its own. No method of safely disposing of this toxic waste has been found, and the volatile nature of the fission reaction can lead to a meltdown of the reactor core if the reaction is not properly controlled. Because of these problems, the future of nuclear power is uncertain.
 
Palace
When populations began to organize their communities into cities, their governments became more structured and formalized. At an early stage, the ruler of the city established headquarters from which the business of running the city was conducted. In many cases, these buildings also served as the living quarters of the ruler. In wealthy cities, these facilities often expanded into immense, sprawling palaces. These richly adorned, imposing buildings were a source of civic pride, and helped to reinforce the aura of power surrounding the ruler.

Power Plant
Power plants burn coal and other fossil fuels to produce the heat and steam necessary to run generators that produce electrical power. When electricity became widely and cheaply available, it meant that industries could convert from steam to electrical power to run their machinery. One central power plant could supply the electrical needs of a relatively large geographic area. However, increasing demands for electricity, by both consumer and commercial customers, led to a rise in the number of power plants. This, in turn, led to problems with air pollution. As more plants went on line, more fossil fuels were burned to generate power. Because modern society depends so heavily on electricity, researchers are constantly searching for alternate forms of energy to satisfy ever-increasing demands.

Recycling Center
The continual growth in city populations leads to an inevitable increase in garbage. Eventually, existing landfills and garbage dumps are  filled, forcing new dumping sites to be established. This leads to the gradual but steady destruction of the local environment. To reverse this problem, many areas have established recycling centers, where much of the garbage is sorted and reduced to reusable components through various means. These components are then used to manufacture new products. In this way, much of the trash produced is turned into raw materials for production, rather than contributing to the ever-increasing pollution problem.

SDI Defense
Historically, research in the area of warfare has seen the development of powerful new weapons closely followed by the development of defenses to counteract the weapons' destructive power. The development of nuclear weapons seemed to be the exception to this rule: for the first time, mankind had created a weapon to which there was apparently no effective defense. SDI (Strategic Defense Initiative), however, could be the answer to this problem. Using laser-equipped orbital satellites or ground-launched ABMs (Anti-Ballistic Missiles) to intercept and destroy enemy nuclear missiles in mid-air, the SDI Defense offers the first hope of negating the threat posed by nuclear missiles.

Spaceship Component
Spaceship components provide the motive power of a spaceship. There are two types: propulsion and fuel. Propulsion components are the spaceship engines, and each fuel component provides enough fuel to run one engine. Every propulsion component requires a fuel component in order to function. At minimum, a spaceship requires one of each type of component. The more engines the spaceship possesses, the faster it  will arrive at its destination.

Spaceship Module
Modules are the central components of a spaceship. There are three types: habitation, life support, and solar panels. Each habitation module provides living space for 10,000 colonists. Each life support module provides enough food, water, and other basic requirements to support the colonists in one habitation module. Both habitation and life support modules require power in order to operate, and each solar panel module provides enough energy to run two other modules. At minimum, every spaceship requires one of each type of module in order to be successful in its mission.

Spaceship Structural
The structural parts of a spaceship are the frame to which all other parts of the spaceship are attached. All spaceship components and modules must be connected to a structural section in order to function. Components and modules not connected to the frame are outlined in red on the spaceship display. 

Temple
In ancient times, almost every city had a temple dedicated to the city's patron god. Many cities also had temples dedicated to other gods as well. In modern times temples are thought of as places of worship, like churches and cathedrals. Ancient societies, however, considered temples to be the local dwelling place for the god or goddess to whom they were dedicated. The faithful citizens brought gifts of food, rare metals, and spices to the temple as a sign of homage and respect. The presence of a temple in the city  had a comforting effect on the population, and wise rulers often constructed one as soon as the city began to grow.

University
Universities are institutions of higher learning. Early universities, established in the Middle Ages, were usually built in cities that had a large or important cathedral. Studies at these institutions focused on matters concerning the church. The curricula quickly expanded to include classical art, literature, and languages. Modern universities provide the opportunity to study a wide array of subjects. They have also become centers for research into many fields, serving as the source of major advances in computers, medicine, physics, and a variety of other subjects.


***New Improvements for Civ 2000***
Airport
Since the middle of the 20th century, the airplane has been one of the chief means of long-distance transport in the world. Nearly every major metropolitan area today has at least one airport, with facilities to handle passengers and ticketing, as well as facilities for refueling and repairing the aircraft that land there. Beginning in the 1940's, the growing role of airplanes as combat vehicles led to the widespread construction of military air bases. Nearly 400 of these facilities in the U.S. alone act as bases and maintenance facilities for aircraft assigned to all branches of the military.

Capitalization
In the business world, companies often need large amounts of cash in order to meet expenses, update facilities, or expand their operations. When there are insufficient funds available to fulfill these needs, these corporations often resort to capitalization in order to raise money. This process involves the sale of a portion of the company's liquid assets. Liquid assets are assets that can be easily converted into cash. These can include surplus raw materials and finished goods, as well as stocks and bonds. The sale of these assets provides the infusion of money needed to meet the company's current needs.

Coastal Fortress
The construction of defensive structures such as city walls and fortified castles dates back to ancient times. City walls were designed primarily to repel an attack launched by ground-based forces, and they performed adequately in such a situation. However, coastal cities were also vulnerable to attack from sea bombardments, since even a city wall left sea ports relatively unprotected. The best way to protect the port was to keep the enemy out of range of the city. This was accomplished by constructing fortresses to cover the approach to the city. These coastal fortresses, built at the mouth of the city's harbor or on barrier islands, would hold enemy vessels at bay, turning away or thinning out the attacking force and minimizing damage to the city's port.

Offshore Platform
Mankind's dependence on wood and coal as a main source of fuel ended when the first commercial oil well went into production in Pennsylvania in 1859. Crude oil could be refined into many different byproducts, and soon replaced wood and coal in many parts of the world. The growing dependence on oil caused the petroleum industry to grow rapidly and wells were drilled all over the world. Most wells were initially drilled on land, but after World War II it was found that many of the largest oil deposits could be found below the sea floor. Shallow water drilling from platforms supported by pylons resting on the seabed proved very successful. Today, large floating platforms can drill for oil at water depths of more than 3300 feet.

Police Stations
The concept of a police force operating independently of the military goes back to the Praetorian Guard of ancient Rome. In the Middle Ages, noblemen protected their estates by appointing constables to enforce the law and to arrest and guard criminals, but the first modern, organized police force was the London Metropolitan Police. Established in 1829, this organization became the model for law enforcement organizations in the United States and many other industrialized nations around the world. The presence of a police force serves to uphold the laws of society, and to control civil unrest. A strong, visible police force strengthens confidence of the community by keeping the citizens safe.

Port Facilities
Seagoing vessels have been used for both commercial transport and military purposes for thousands of years. Cities built on rivers and on the coasts of seas and oceans built facilities to receive cargo and to house military vessels stationed in the area. Many of the larger cities built large port facilities that included shipyards for the construction of new vessels, large warehouse and docking facilities, and dry-docks for the repair of damaged vessels. Heavily damaged ships can be repaired much more quickly when such facilities are available.

Research Lab
Historically, libraries and universities have acted as the primary centers of research for new ideas and technologies. The growth of private industry in the modern age has also given birth to hundreds of privately-owned research facilities. These private laboratories, usually dedicated to research in a single field related to their founding company, have made tremendous advances in many fields including physics, biology, chemistry, and medicine. The growth of privately-funded  research has vastly increased the speed at which mankind achieves new advances in science and technology.

SAM Missile Battery
The use of airplanes in warfare began in earnest during World War I. By the end of World War II, the use of fighter aircraft and bombers was commonplace and the importance of air warfare continued to grow, as did the importance of effective anti-aircraft defenses. During the 1950's, the refinement of rocket technology allowed for the construction of compact missiles which were used to deliver explosive warheads to their targets swiftly and accurately. Batteries of surface-to-air missiles, or SAMs, were built to protect cities and ground installations against airborne attacks. The long range and high accuracy of SAM batteries provided a much more effective defense than the anti-aircraft guns of World War II.

Sewer System
One of the byproducts of large urban centers is a vast amount of human waste. As the city continues to grow, steps need to be taken to move the sewage away from inhabited areas and "treat" it so that it does not become a health hazard to humans or harm the local ecosystem. Sewer systems carry wastewater to treatment plants where the raw sewage is broken down through filtration and chemical processes to remove solids and harmful bacteria. The treated byproduct is then released into rivers and other waterways, where it is eventually washed safely into the ocean.

Solar Power Plant
One of the greatest natural sources of energy available on Earth is the sun. Solar energy can be converted directly into electrical power without the need for mechanical generators through the use of photoelectric cells. Alternatively, large solar collectors known as heliostats can be used to focus solar energy into a water boiler, generating steam to run conventional electrical turbines. Unfortunately, at our current level of technology, both of these systems are prohibitively expensive to construct. However, because of  the dwindling supply of fossil fuels and increasing concern over the pollution produced by conventional and nuclear power plants, scientists are constantly working on a viable way to harness the clean and endless supply of energy provided by our sun.

Stock Exchange
In a free market economy, corporations often raise operating and development capital by selling "shares" in the corporation to private investors. These shares, which allow investors to share in the company's profits, were originally sold by brokers and privately hired auctioneers. Early European stock exchanges, such as the Paris Bourse, allowed anyone to buy and sell stock. However, it was quickly discovered that a formalized system was necessary in order to enforce transactions. Thereafter, membership in the exchange was required in order to buy and sell. The first formal stock exchange in the U.S. was established in 1791 in Philadelphia, and the New York Stock Exchange was established a year later. Today, stock exchanges are located in many major cities and commercial centers around the world. Private investment in corporations is vital to capitalistic economies, allowing corporations to grow more quickly than would otherwise be possible. The profits and new jobs created as a result improve the economy as a whole.

Supermarket
Supermarkets are large, self-service retail stores that sell a wide variety of food items and household goods  to the general public. The first true supermarket, King Kullen, was established in 1930 in the borough of Queens, New York City, by Michael Cullen. Improved storage techniques and refrigeration allowed supermarkets to stock and sell perishable foods in large quantities, reducing the price to the consumer. The combination of ready availability and low prices made the supermarket an instant success in the U.S. during the years of the Great Depression.  The supermarket continues to grow in popularity in countries around the world.

Superhighway
Early in his career, President Eisenhower traveled by road, from coast to coast, across the United States. This trip, which took nearly a month because of the poor system of roads, convinced him that it was necessary to make all areas of the country easily accessible. Not only were these improvements important to the growing number of people traveling by automobile, they could prove invaluable for the movement of troops and military equipment should the need arise. In 1956, Eisenhower established a federal-aid program known as the Highway Trust Fund to accelerate the construction of a network of interstate roads. By 1991, the Interstate Highway System in the U.S. consisted of over 42,000 miles of highways. Unlike local roadways, superhighways were designed to bypass large population centers, and were accessible in limited locations at planned entrance and exit interchanges. These highly efficient roadways allow motorists today to travel from one end of the country to the other without having to slow down for intersections and traffic signals.

Harbor
Just because a city is built in a coastal region doesn't guarantee that the city is readily accessible by ship. In order for a port city to establish a steady trade, fishing, or other shipping industry, the city must have a harbor. A harbor is a protected body of water that opens into an ocean or lake that shelters ships from waves and high winds. Although some coastal cities are established in areas where a natural harbor exists, most seaports are forced either to improve the existing natural harbor, or to build a man-made harbor to shelter ships and provide channels deep enough to accommodate large vessels.
